Repository javiermanzo/Harbor, pull requests merged in 2024-11, with the labels that each got.

#29 Swift 6 Sendable compatibility + Single URL Session between calls
  .github/workflows/swift.yml
  Example/HarborExample/Requests/JRPCRequest.swift
  Example/HarborExample/RequestsView.swift
  Package.swift
  README.md
  Sources/Harbor/HAuthProviderProtocol.swift
  Sources/Harbor/HConfig.swift
  Sources/Harbor/HDebugRequestProtocol.swift
  Sources/Harbor/HRequestManager.swift
  Sources/Harbor/HRequestProtocol.swift
  Sources/Harbor/Harbor.swift
  Sources/Harbor/HmTLS.swift
  Sources/HarborJRPC/HJRPCConfig.swift
  Sources/HarborJRPC/HJRPCRequestManager.swift
  Sources/HarborJRPC/HJRPCRequestProtocol.swift
  Sources/HarborJRPC/HJSONRPCResponse.swift
  Sources/HarborJRPC/HarborJRPC.swift
  Tests/HarborJRPCTests/HarborJRPCTests.swift
  Tests/HarborTests/HarborBodyTests.swift
  Tests/HarborTests/HarborRequestManagerAuthTests.swift
  Tests/HarborTests/HarborTests.swift
  Tests/HarborTests/Mocks/MocksRequest.swift
Labels: enhancement, improvement

#30 Update repository badges
  README.md
Labels: documentation

#31 Mock Harbor requests
  README.md
  Sources/Harbor/HConfig.swift
  Sources/Harbor/HRequestManager.swift
  Sources/Harbor/HRequestProtocol.swift
  Sources/Harbor/Harbor.swift
  Sources/Harbor/Mock/HMock.swift
  Sources/Harbor/Mock/HMocker.swift
  Sources/Harbor/Utils/NSMutableData-extension.swift
  Sources/HarborJRPC/HJRPCRequestManager.swift
  Sources/HarborJRPC/HJRPCRequestProtocol.swift
  Sources/HarborJRPC/HJSONRPCResponse.swift
  Tests/HarborTests/HarborBodyTests.swift
  Tests/HarborTests/HarborMockTests.swift
  Tests/HarborTests/HarborRequestManagerAuthTests.swift
  Tests/HarborTests/HarborTests.swift
  Tests/HarborTests/Mocks/MockModel.swift
  Tests/HarborTests/Mocks/MocksRequest.swift
Labels: documentation, enhancement, test

#32 Update README for the configuration of a custom URLSession
  README.md
  Sources/Harbor/HConfig.swift
  Sources/Harbor/HRequestManager.swift
  Sources/Harbor/Harbor.swift
Labels: documentation

#33 Release/2.0.0
  .github/workflows/swift.yml
  Example/HarborExample/Requests/JRPCRequest.swift
  Example/HarborExample/RequestsView.swift
  Harbor.podspec
  Package.swift
  README.md
  Sources/Harbor/HAuthProviderProtocol.swift
  Sources/Harbor/HConfig.swift
  Sources/Harbor/HDebugRequestProtocol.swift
  Sources/Harbor/HRequestManager.swift
  Sources/Harbor/HRequestProtocol.swift
  Sources/Harbor/Harbor.swift
  Sources/Harbor/HmTLS.swift
  Sources/Harbor/Mock/HMock.swift
  Sources/Harbor/Mock/HMocker.swift
  Sources/Harbor/Utils/NSMutableData-extension.swift
  Sources/HarborJRPC/HJRPCConfig.swift
  Sources/HarborJRPC/HJRPCRequestManager.swift
  Sources/HarborJRPC/HJRPCRequestProtocol.swift
  Sources/HarborJRPC/HJSONRPCResponse.swift
  Sources/HarborJRPC/HarborJRPC.swift
  Tests/HarborJRPCTests/HarborJRPCTests.swift
  Tests/HarborTests/HarborBodyTests.swift
  Tests/HarborTests/HarborMockTests.swift
  Tests/HarborTests/HarborRequestManagerAuthTests.swift
  Tests/HarborTests/HarborTests.swift
  Tests/HarborTests/Mocks/MockModel.swift
  Tests/HarborTests/Mocks/MocksRequest.swift
Labels: release
